### ISSUE TITLE
App doesn´t render after creation of hooks and validations for input fields.

### ISSUE THREAD

**Issue by aronvaupel** [aronvaupel/SwapIt-Capstone#41]
Hey guys,
pls help me solve my blockade.
My vite-app on port 3000 doesn't render anymore. This occured after I implemented the useState and validation function suggested by the coach.
In vscode I have no problems detected and in the dev tools I get the following error message:
GET http://localhost:3000/node_modules/.vite/chunk-W26VLEWB.js?v=08380ecd net::ERR_ABORTED 404 (Not Found)

**Comment by macfrei** [comment]
Could you use the question template and add more information? It would help to give you an answer and better understand your problem 🙂

**Comment by phlgr** [comment]
Please create an issue [here ](https://github.com/neuefische/help/issues) with the provided template.
